# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/lt02wifi/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/samsung/lt02wifi/proprietary/lib/libsecril-client.so:obj/lib/libsecril-client.so \
    vendor/samsung/lt02wifi/proprietary/lib/libril.so:obj/lib/libril.so

PRODUCT_COPY_FILES += \
    vendor/samsung/lt02wifi/proprietary/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \
    vendor/samsung/lt02wifi/proprietary/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \
    vendor/samsung/lt02wifi/proprietary/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so \
    vendor/samsung/lt02wifi/proprietary/lib/libGAL.so:system/lib/libGAL.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/audio.primary.mrvl.so:system/lib/hw/audio.primary.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/audio_path.adda.mrvl.so:system/lib/hw/audio_path.adda.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/audio_path.fm.mrvl.so:system/lib/hw/audio_path.fm.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/audio_path.hifi.mrvl.so:system/lib/hw/audio_path.hifi.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/audio_path.vc.mrvl.so:system/lib/hw/audio_path.vc.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/audio_path.voip.mrvl.so:system/lib/hw/audio_path.voip.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/audio_path.vt.mrvl.so:system/lib/hw/audio_path.vt.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/audio_policy.mrvl.so:system/lib/hw/audio_policy.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/libacoustic.so:system/lib/libacoustic.so \
    vendor/samsung/lt02wifi/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/samsung/lt02wifi/proprietary/lib/libaudiodebugtool.so:system/lib/libaudiodebugtool.so \
    vendor/samsung/lt02wifi/proprietary/lib/liblvvewrapper.so:system/lib/liblvvewrapper.so \
    vendor/samsung/lt02wifi/proprietary/lib/libMarvellWireless.so:system/lib/libMarvellWireless.so \
    vendor/samsung/lt02wifi/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/lt02wifi/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/lt02wifi/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/camera.mrvl.so:system/lib/hw/camera.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/libcameraengine.so:system/lib/libcameraengine.so \
    vendor/samsung/lt02wifi/proprietary/lib/libcodecjpegdec.so:system/lib/libcodecjpegdec.so \
    vendor/samsung/lt02wifi/proprietary/lib/libcodecjpegenc.so:system/lib/libcodecjpegenc.so \
    vendor/samsung/lt02wifi/proprietary/lib/libmiscgen.so:system/lib/libmiscgen.so \
    vendor/samsung/lt02wifi/proprietary/lib/libphycontmem.so:system/lib/libphycontmem.so \
    vendor/samsung/lt02wifi/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/lt02wifi/proprietary/lib/libsocketsvr.so:system/lib/libsocketsvr.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/sensors.mrvl.so:system/lib/hw/sensors.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/lt02wifi/proprietary/etc/AGPS_CA.pem:system/etc/AGPS_CA.pem \
    vendor/samsung/lt02wifi/proprietary/lib/hw/csr.cpd.so:system/lib/hw/csr.cpd.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/lights.mrvl.so:system/lib/hw/lights.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/gralloc.mrvl.so:system/lib/hw/gralloc.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/hwcomposer.mrvl.so:system/lib/hw/hwcomposer.mrvl.so \
    vendor/samsung/lt02wifi/proprietary/lib/libHWComposerGC.so:system/lib/libHWComposerGC.so \
    vendor/samsung/lt02wifi/proprietary/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/lt02wifi/proprietary/lib/hw/nfc.pxa988.so:system/lib/hw/nfc.pxa988.so \
    vendor/samsung/lt02wifi/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/samsung/lt02wifi/proprietary/vendor/firmware/libpn547_fw_eng.so:system/vendor/firmware/libpn547_fw_eng.so \
    vendor/samsung/lt02wifi/proprietary/vendor/firmware/libpn547_fw_platform.so:system/vendor/firmware/libpn547_fw_platform.so
